Added HAVE_BLAS define to config.h.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -7,7 +7,9 @@ PREFIX="/usr/local"
 MPIR_DIR="/usr"
 MPFR_DIR="/usr"
 NTL_DIR="/usr"
+BLAS_DIR="/usr"
 WANT_NTL=0
+WANT_BLAS=0
 SHARED=1
 STATIC=1
 REENTRANT=0
@@ -22,6 +24,7 @@ usage()
    echo "   where <args> may be:"
    echo "     --with-mpir=<path> Specify location of MPIR"
    echo "     --with-mpfr=<path> Specify location of MPFR"
+   echo "     --with-blas=<path> Specify location of BLAS"
    echo "     --with-ntl=<path>  Specify location of NTL and build NTL interface"
    echo "     --build=arch-os    Specify architecture/OS combination rather than use values from uname -m/-s"
    echo "     --prefix=<path>    Specify path to installation location"
@@ -51,6 +54,10 @@ while [ "$1" != "" ]; do
       --with-ntl)
          NTL_DIR=$VALUE
          WANT_NTL=1
+         ;;
+      --with-blas)
+         BLAS_DIR=$VALUE
+         WANT_BLAS=1
          ;;
       --build)
          BUILD=$VALUE
@@ -133,11 +140,25 @@ else
    exit 1
 fi
 
+if [ -d "${BLAS_DIR}" ]; then
+   BLAS_LIB_DIR="${BLAS_DIR}"
+   BLAS_INCLUDE_DIR="${BLAS_DIR}"
+else
+   echo "Invalid BLAS directory"
+   exit 1
+fi
+
 #configure extra libraries
 
 if [ "$WANT_NTL" = "1" ]; then
     EXTRA_LIBS="$EXTRA_LIBS -lntl"
 fi
+
+if [ "$WANT_BLAS" = "1" ]; then
+    EXTRA_LIBS="$EXTRA_LIBS -lopenblas"
+fi
+    
+CONFIG_DEFINES="${CONFIG_DEFINES}\n#define HAVE_BLAS ${WANT_BLAS}"
 
 #name for FLINT shared library
 
@@ -275,7 +296,7 @@ echo "int main(int argc, char ** argv) {return __builtin_popcountl(argc) == 100;
 $CC build/test-popcnt.c -o ./build/test-popcnt > /dev/null 2>&1
 if [ $? -eq 0 ]; then
    echo "yes"
-   CONFIG_DEFINES="$CONFIG_DEFINES #define POPCNT_INTRINSICS"
+   CONFIG_DEFINES="${CONFIG_DEFINES}\n#define POPCNT_INTRINSICS"
 
    if [ "$MACHINE" = "x86_64" ]; then
       MSG="Testing native popcount..."
@@ -322,6 +343,8 @@ echo "WANT_NTL=$WANT_NTL" >> Makefile
 echo "EXTRA_LIBS=$EXTRA_LIBS" >> Makefile
 echo "FLINT_MPIR_LIB_DIR=$MPIR_LIB_DIR" >> Makefile
 echo "FLINT_MPIR_INCLUDE_DIR=$MPIR_INCLUDE_DIR" >> Makefile
+echo "FLINT_BLAS_LIB_DIR=$BLAS_LIB_DIR" >> Makefile
+echo "FLINT_BLAS_INCLUDE_DIR=$BLAS_INCLUDE_DIR" >> Makefile
 echo "FLINT_MPFR_LIB_DIR=$MPFR_LIB_DIR" >> Makefile
 echo "FLINT_MPFR_INCLUDE_DIR=$MPFR_INCLUDE_DIR" >> Makefile
 echo "FLINT_NTL_LIB_DIR=$NTL_LIB_DIR" >> Makefile
